development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: nomidwow@gmail.com
  :password: lvbnhbq007
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: nomidwow@gmail.com
  :password: lvbnhbq007
  :enable_starttls_auto: true